dist: jammy
language: node_js
node_js:
  - 18

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: 18
      script: yarn build
      deploy:
        on:
          branch: main
        provider: script
        skip_cleanup: true
        script: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release


