language: node_js
node_js:
  - 18
jobs:
  include:
    - stage: release
      install:
        - yarn install
      deploy:
        provider: script
        script:
          - yarn build
          - npx semantic-release