language: node_js
node_js:
  - 16
script:
  - yarn build
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        script:
          - npx semantic-release