language: node_js
node_js:
  - 16
jobs:
  include:
    - stage: release
      node_js: 16
      deploy:
        provider: script
        script:
          - yarn build
          - npx semantic-release