jobs:
  include:
    - stage: release
      node_js: 18
      install:
        - yarn install
      deploy:
        provider: script
        script:
          - yarn build
          - npx semantic-release